### ISSUE TITLE
Incorporate upstream feedback updates

### ISSUE THREAD

**Issue by nate-double-u** [containernetworking/cni.dev#20]
- [x] Update colour scheme (similar to https://github.com/dexidp/website/issues/58)
- [x] Add Github Button to Top Level Nav (similar to https://github.com/dexidp/website/issues/57)
- [x] Move Docs Navigation to the Left Side of Pages (similar to https://github.com/dexidp/website/issues/56)
- [x] Add smoke test page (similar to https://github.com/cncf/hugo-netlify-starter/issues/54)
- [x] Update copyright footer & bottom of homepage (similar to https://github.com/dexidp/website/pull/34, https://github.com/cncf/hugo-netlify-starter/pull/40)
