### ISSUE TITLE
CNCF Website Guidelines Checklist

### ISSUE THREAD

**Issue by nate-double-u** [containernetworking/cni.dev#6]
As per the [CNCF Website Guidelines](https://github.com/cncf/foundation/blob/master/website-guidelines.md):

- [x] 1. Website should be hosted in an open source repo
  - [x] Hosted in the same organization as the main project
- [x] 2. Reference the origin company correctly
  *Note*: It is OK to say that, e.g., “Prometheus was originally created by Soundcloud” or “Kubernetes builds upon 15 years of experience of running production workloads at Google,” but the origin company should not otherwise be referred to on the project homepage.
- [x] 3. No links or forms for capturing enterprise support leads present.
  It is fine to have an enterprise support, commercial partners or similar page.
  - [ ] If page is present, the companies list is alphabetized or randomized on load.
  - [ ] If page is present, the vetting of companies listed is complete
    *Note*: Projects are welcome to outsource this vetting to CNCF staff if it becomes a burden.
- [x] 4. Links to companies offering support go to a page that at least mentions support of the project
- [x] 5. Copyright notice present at bottom of page.
  Copyright to the project authors or to CNCF, not the origin company.
- [x] 6. CNCF Branding elements
  - [x] “We are a Cloud Native Computing Foundation project.” or “We are a Cloud Native Computing Foundation sandbox project.” present (depending on status)  
  - [x] CNCF logo near the bottom of their project homepage  
  - [x] (optional) link to KubeCon + CloudNativeCon as the events approach  
- [x] 7. Footer contains:
  "Copyright The Linux Foundation. All rights reserved. The Linux Foundation has registered trademarks and uses trademarks. For a list of trademarks of The Linux Foundation, please see our [Trademark Usage](https://www.linuxfoundation.org/trademark-usage/) page."

**Comment by nate-double-u** [comment]
Some of these may not be applicable.
